"""add column lead_memory segment

Revision ID: 07bf6ae11bb4
Revises: 1ac8a3f5be05
Create Date: 2025-08-13 08:36:11.004048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bf6ae11bb4'
down_revision: Union[str, Sequence[str], None] = '1ac8a3f5be05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_memory', sa.Column('segment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_memory', 'segment')
    # ### end Alembic commands ###
