"""add followup_count and last_followup_at

Revision ID: 1ac8a3f5be05
Revises: ed17f4e99815
Create Date: 2025-08-12 16:07:44.595796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac8a3f5be05'
down_revision: Union[str, Sequence[str], None] = 'ed17f4e99815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followup_state', sa.Column('followup_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('followup_state', sa.Column('last_followup_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followup_state', 'last_followup_at')
    op.drop_column('followup_state', 'followup_count')
    # ### end Alembic commands ###
