"""criação da tabela X

Revision ID: 1c44e3a89de0
Revises: 662feb936207
Create Date: 2025-08-07 16:57:38.053491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c44e3a89de0'
down_revision: Union[str, Sequence[str], None] = '662feb936207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_memory', sa.Column('uf', sa.String(length=10), nullable=True))
    op.add_column('lead_memory', sa.Column('cidade', sa.String(length=255), nullable=True))
    op.add_column('lead_memory', sa.Column('quantidade_usuarios', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_memory', 'quantidade_usuarios')
    op.drop_column('lead_memory', 'cidade')
    op.drop_column('lead_memory', 'uf')
    # ### end Alembic commands ###
