"""adjusted chunk table

Revision ID: 22c44ccf27f6
Revises: 5ef728148f60
Create Date: 2025-08-03 22:01:50.419402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c44ccf27f6'
down_revision: Union[str, Sequence[str], None] = '5ef728148f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('document_id', sa.Integer(), nullable=True))
    op.add_column('chunk', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('chunk', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('chunk_documento_id_fkey'), 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'document', ['document_id'], ['id'])
    op.drop_column('chunk', 'documento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('documento_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_documento_id_fkey'), 'chunk', 'document', ['documento_id'], ['id'])
    op.drop_column('chunk', 'updated_at')
    op.drop_column('chunk', 'created_at')
    op.drop_column('chunk', 'document_id')
    # ### end Alembic commands ###
