"""add metadata fields to chunk table

Revision ID: 6d44f1912a4e
Revises: 12398206abfa
Create Date: 2025-08-05 14:53:05.012526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d44f1912a4e'
down_revision: Union[str, Sequence[str], None] = '12398206abfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('section_title', sa.String(length=255), nullable=True))
    op.add_column('chunk', sa.Column('chunk_position', sa.String(length=20), nullable=True))
    op.add_column('chunk', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'token_count')
    op.drop_column('chunk', 'chunk_position')
    op.drop_column('chunk', 'section_title')
    # ### end Alembic commands ###
