"""ajuste tabela de leads

Revision ID: c4474776011e
Revises: ef7390784c8f
Create Date: 2025-08-09 15:31:10.611037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4474776011e'
down_revision: Union[str, Sequence[str], None] = 'ef7390784c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_memory', sa.Column('videos_enviados', sa.String(length=500), nullable=True))
    op.add_column('lead_memory', sa.Column('desafios', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_memory', 'desafios')
    op.drop_column('lead_memory', 'videos_enviados')
    # ### end Alembic commands ###
