"""create followup_state table1

Revision ID: ed17f4e99815
Revises: 14c344648e64
Create Date: 2025-08-12 15:57:14.130456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed17f4e99815'
down_revision: Union[str, Sequence[str], None] = '14c344648e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followup_state',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('last_actor', sa.String(), nullable=True),
    sa.Column('last_ai_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_confirmed', sa.Boolean(), nullable=True),
    sa.Column('followup_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followup_state')
    # ### end Alembic commands ###
