"""add nome do sistema atual

Revision ID: ef7390784c8f
Revises: 1c44e3a89de0
Create Date: 2025-08-07 17:55:38.794561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7390784c8f'
down_revision: Union[str, Sequence[str], None] = '1c44e3a89de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_memory', sa.Column('sistema_atual', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_memory', 'sistema_atual')
    # ### end Alembic commands ###
